import { FaClockRotateLeft } from "react-icons/fa6";
import { BsFire } from "react-icons/bs";
import { AiFillThunderbolt } from "react-icons/ai";
import { FaTags, FaStar } from "react-icons/fa";

import { ProductType } from "@/modules/homePage/homePage.types";


export const JWT_SECRET = "eregr5trertw56rrgfhtyrt5tfasrgt235346346ffgsdfgdfsg4dfefsdrwef"

export const TABS_DATA = [
  { id: 1, name: "Recently Viewed", keyWord: "recently_viewed", icon: FaClockRotateLeft },
  { id: 2, name: "Weekly Deals", keyWord: "weekly_deals", icon: AiFillThunderbolt },
  { id: 3, name: "Hot Deals", keyWord: "hot_deals", icon: BsFire },
  { id: 4, name: "Top Brands", keyWord: "top_brands", icon: FaStar },
  { id: 5, name: "Choice", keyWord: "choice", icon: FaTags },
];

export const SLIDE_IMAGES = [
  {
    id: 1,
    url: "/SI1.webp",
    alt: "Slide 1",
  },
  {
    id: 2,
    url: "/SI2.webp",
    alt: "Slide 2",
  },
  {
    id: 3,
    url: "/SI3.webp",
    alt: "Slide 3",
  },
  {
    id: 4,
    url: "/SI4.webp",
    alt: "Slide 4",
  },
];

export const GIVEAWAY_IMAGES = [
  {
    id: 1,
    src: '/G1.webp',
    alt: 'Giveaway Item 1',
    href: '/',
  },
  {
    id: 2,
    src: '/G2.webp',
    alt: 'Giveaway Item 2',
    href: '/',
  },
  {
    id: 3,
    src: '/G3.webp',
    alt: 'Giveaway Item 3',
    href: '/',
  },
  {
    id: 4,
    src: '/G4.webp',
    alt: 'Giveaway Item 4',
    href: '/',
  },
];

export const CATEGORIES = [
  {
    id: 1,
    src: '/C1.webp',
    alt: 'Giveaway Item 1',
    href: '/',
  },
  {
    id: 2,
    src: '/C2.webp',
    alt: 'Giveaway Item 2',
    href: '/',
  },
  {
    id: 3,
    src: '/C3.webp',
    alt: 'Giveaway Item 3',
    href: '/',
  },
  {
    id: 4,
    src: '/C4.webp',
    alt: 'Giveaway Item 4',
    href: '/',
  },
];

export const PRODUCTS: ProductType[] = [
  {
    id: 1,
    image: "/P11.jpg",
    itemName: "4-Piece Sofa Set with Cushions",
    price: 699.99,
    ratings: 4.3,
    category: "Home & Garden",
    itemType: "Furniture",
    description: "Elegant outdoor patio furniture set perfect for gardens, patios, and balconies.",
    reviews: 85,
    soldQuantity: 180,
  },
  {
    id: 2,
    image: "/P2.jpg",
    itemName: "iPhone 14 Pro Max 256GB",
    price: 1199.99,
    ratings: 4.8,
    category: "Mobile Phones",
    itemType: "Smartphone",
    description: "Latest iPhone with A16 Bionic chip, ProMotion display and incredible camera system.",
    reviews: 210,
    soldQuantity: 350,
  },
  {
    id: 3,
    image: "/P12.jpg",
    itemName: "King Size Comforter Set",
    price: 149.99,
    ratings: 4.6,
    category: "Home & Garden",
    itemType: "Bedding",
    description: "Luxury soft comforter set with pillow shams and quilted stitching.",
    reviews: 102,
    soldQuantity: 300,
  },
  {
    id: 4,
    image: "/P4.jpg",
    itemName: "Canon EOS R50 Mirrorless Camera",
    price: 699.00,
    ratings: 4.6,
    category: "Cameras",
    itemType: "Mirrorless Camera",
    description: "Compact mirrorless camera perfect for creators, with 4K video and interchangeable lenses.",
    reviews: 95,
    soldQuantity: 120,
  },
  {
    id: 5,
    image: "/P13.jpg",
    itemName: "Men’s Waterproof Windbreaker Jacket",
    price: 89.99,
    ratings: 4.4,
    category: "Clothes",
    itemType: "Outerwear",
    description: "Lightweight, stylish and breathable windbreaker with adjustable hood.",
    reviews: 95,
    soldQuantity: 220,
  },
  {
    id: 6,
    image: "/P6.jpg",
    itemName: "Nike Air Max 270 Sneakers",
    price: 149.95,
    ratings: 4.4,
    category: "Footwear",
    itemType: "Sneakers",
    description: "Stylish and comfortable everyday shoes with responsive cushioning and breathable mesh.",
    reviews: 85,
    soldQuantity: 200,
  },
  {
    id: 7,
    image: "/P7.jpg",
    itemName: "Fossil Gen 6 Smartwatch",
    price: 249.99,
    ratings: 4.2,
    category: "Wearables",
    itemType: "Smartwatch",
    description: "Sleek Android-compatible watch with fitness tracking, notifications, and fast charging.",
    reviews: 70,
    soldQuantity: 90,
  },
  {
    id: 8,
    image: "/P8.jpg",
    itemName: "Dyson V15 Detect Cordless Vacuum",
    price: 749.00,
    ratings: 4.8,
    category: "Home Appliances",
    itemType: "Vacuum Cleaner",
    description: "Powerful cordless vacuum with laser dust detection and advanced filtration system.",
    reviews: 130,
    soldQuantity: 230,
  },
  {
    id: 9,
    image: "/P9.jpg",
    itemName: "LEGO Star Wars Millennium Falcon",
    price: 159.99,
    ratings: 4.9,
    category: "Toys",
    itemType: "Building Set",
    description: "1,351-piece LEGO set of the iconic Star Wars ship. Great for ages 9+.",
    reviews: 95,
    soldQuantity: 170,
  },
  {
    id: 10,
    image: "/P10.jpg",
    itemName: "Maybelline Fit Me Matte Foundation",
    price: 9.99,
    ratings: 4.3,
    category: "Beauty",
    itemType: "Cosmetics",
    description: "Lightweight foundation with a matte finish and natural coverage for daily use.",
    reviews: 200,
    soldQuantity: 300,
  },
  {
    id: 11,
    image: "/P1.jpg",
    itemName: "Samsung 55\" QLED Smart TV",
    price: 899.99,
    ratings: 4.5,
    category: "Electronics",
    itemType: "Television",
    description: "Stunning 4K QLED display with Smart features including Netflix, YouTube and Alexa integration.",
    reviews: 120,
    soldQuantity: 240,
  },
  {
    id: 12,
    image: "/P3.jpg",
    itemName: "MacBook Air M2 13-inch",
    price: 1299.00,
    ratings: 4.7,
    category: "Computers",
    itemType: "Laptop",
    description: "Ultra-light Apple laptop with M2 chip and Retina display for blazing performance.",
    reviews: 180,
    soldQuantity: 400,
  },
  {
    id: 13,
    image: "/P5.jpg",
    itemName: "Sony WH-1000XM5 Wireless Headphones",
    price: 349.99,
    ratings: 4.9,
    category: "Audio",
    itemType: "Headphones",
    description: "Industry-leading noise cancellation and premium sound with up to 30 hours battery life.",
    reviews: 310,
    soldQuantity: 600,
  },
  {
    id: 14,
    image: "/P7.jpg",
    itemName: "Women’s High Waist Yoga Leggings",
    price: 39.99,
    ratings: 4.7,
    category: "Clothes",
    itemType: "Activewear",
    description: "Comfortable stretch leggings perfect for yoga, gym or casual wear.",
    reviews: 130,
    soldQuantity: 410,
  },
  {
    id: 15,
    image: "/P8.jpg",
    itemName: "Kids’ Wooden Puzzle Set (6-in-1)",
    price: 24.99,
    ratings: 4.9,
    category: "Children",
    itemType: "Toys",
    description: "Educational and fun puzzles designed for children aged 3–6.",
    reviews: 145,
    soldQuantity: 270,
  },
  {
    id: 16,
    image: "/P9.jpg",
    itemName: "Baby Stroller with Adjustable Canopy",
    price: 229.00,
    ratings: 4.5,
    category: "Children",
    itemType: "Gear",
    description: "Comfortable, lightweight stroller with shock-absorbing wheels and recline function.",
    reviews: 78,
    soldQuantity: 140,
  },
  {
    id: 17,
    image: "/P10.jpg",
    itemName: "Orthopedic Memory Foam Dog Bed",
    price: 59.99,
    ratings: 4.8,
    category: "Pets",
    itemType: "Pet Supplies",
    description: "Soft and supportive bed for small to medium dogs, machine washable cover included.",
    reviews: 160,
    soldQuantity: 320,
  }
];
